FROM python:3.13-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/


WORKDIR /app
COPY pyproject.toml uv.lock ./

RUN uv sync

COPY . .

EXPOSE 8000


CMD ["uv", "run", "app/main.py"]
